<?php

$order = $block->getOrder();
$bSecureOrderLink = $block->getBsecureOrderLink($order);

$bsecureOrderId = $order->getData("bsecure_order_id");
$bsecureOrderRef = $order->getData("bsecure_order_ref");
    
if (!empty($bsecureOrderId) && !empty($bsecureOrderRef)) { ?>
   <h2><a href="<?= $block->escapeJsQuote($bSecureOrderLink); ?>" 
       target="_blank"><?= $block->escapeHtmlAttr(__('View order on bSecure')); ?></a></h2>
<?php }
