<?php

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Checkout\Block\Cart\Sidebar */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */

?>


<div id="cart-page">
   <div id="block-cart-list" data-bind="scope:'minicart-addons'" class="">
           <div class="bsecure-minicart-btn-wrapper" data-bind="if: getTotalCartItems() > 0" align="center">

       <?php
        $bsecureHelper      = $block->getBsecureHelper();
        $cartHelper         = $block->getCartHelper();
        $title              = $block->
                              getBsecureSettings('bsecure_title');
        $moduleEnabled      = $block->
                              getBsecureSettings('enable');
        $showCheckoutBtn    = $block->
                              getBsecureSettings('show_checkout_btn');
        
        if ($block->getCartCount() > 0) {
            if ($showCheckoutBtn == $bsecureHelper::BTN_SHOW_BSECURE_BOTH && $moduleEnabled) {
                ?>               
                <a href="javascript:;" class="minicart-area bsecure-checkout-button">
                  <img    data-role="proceed-to-checkout"
                    title="<?= $block->escapeHtmlAttr($title); ?>"
                    alt="<?= $block->escapeHtmlAttr($title); ?>"            
                    class="primary checkout"
                    src="<?=
                    $block->escapeHtmlAttr($block->getViewFileUrl($bsecureHelper::BTN_BUY_WITH_BSECURE));
                    ?>"
                     />
                </a>

            <?php }
        } ?>
       </div>

       <!-- ko template: getTemplate() --><!-- /ko -->
       <script type="text/x-magento-init">
         {
             "#block-cart-list": {
                 "Magento_Ui/js/core/app": <?= $block->getJsLayout(); ?>
             }
         }
     </script>

     <script type="text/javascript">
    require([
        'Magento_Customer/js/customer-data'
    ], function (customerData) {
        'use strict';

        customerData.get('cart').subscribe(function (cartInfo) {
            console.log('summary_count: ',cartInfo['summary_count']);
        }, this);
    });
</script>
   </div>
</div>


