<?php 

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Checkout\Block\Cart\Sidebar */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
?>


<div id="cart-page">
   <div id="block-cart-list" data-bind="scope:'minicart-addons'" class="block">
           <div class="" data-bind="if: getTotalCartItems() > 0" align="center">

       <?php

        $cartHelper         = $this->helper('Magento\Checkout\Helper\Cart');    
        $helper             = $this->helper('Bsecure\UniversalCheckout\Helper\Data');    
        $title              = $helper->getConfig('universalcheckout/general/bsecure_title');
        $moduleEnabled      = $helper->getConfig('universalcheckout/general/enable');
        $showCheckoutBtn    = $helper->getConfig('universalcheckout/general/show_checkout_btn');
        
        if ($cartHelper->getSummaryCount() > 0) {
            if ($showCheckoutBtn == $helper::BTN_SHOW_BSECURE_BOTH && $moduleEnabled) {
                ?>
                
                <a href="javascript:;" class="minicart-area bsecure-checkout-button">
                  <img    data-role="proceed-to-checkout"
                    title="<?php echo  $block->escapeHtmlAttr($title); ?>"
                    alt="<?php echo  $block->escapeHtmlAttr($title); ?>"            
                    class="primary checkout"
                    src="<?php 
                    echo $block->escapeHtmlAttr($this->getViewFileUrl('Bsecure_UniversalCheckout::images/buy-with-bsecure-black.svg'));//phpcs:ignore
                     ?>"
                     />
                </a>

            <?php }
        } ?>
       </div>

       <!-- ko template: getTemplate() --><!-- /ko -->
       <script type="text/x-magento-init">
         {
             "#block-cart-list": {
                 "Magento_Ui/js/core/app": <?php  echo /* @codingStandardsIgnoreStart */ $block->getJsLayout(); /* @codingStandardsIgnoreEnd */?>
             }
         }
     </script>
   </div>
</div>


