<?php 

//Upon success clear the minin cart data from cache//

?>


<script type='text/javascript'>
    window.addEventListener( 'load', function( event ) {
        require([
               'Magento_Customer/js/customer-data'
            ], function (customerData) {
            var sections = ['cart'];
            customerData.invalidate(sections);
            customerData.reload(sections, true);
        });
    });
</script>
