<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Checkout\Block\Cart\Sidebar */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
?>


<div id="cart-page">
   <div id="block-cart-list" data-bind="scope:'minicart-addons'" class="block">
   		<div class="" data-bind="if: getTotalCartItems() > 0" align="center">

   	<?php

		$cartHelper 		= $this->helper('Magento\Checkout\Helper\Cart');	
		$helper 			= $this->helper('Bsecure\UniversalCheckout\Helper\Data');	
		$title 				= $helper->getConfig('universalcheckout/general/bsecure_title');
		$module_enabled 	= $helper->getConfig('universalcheckout/general/enable');
		$show_checkout_btn 	= $helper->getConfig('universalcheckout/general/show_checkout_btn');
		
		if ($cartHelper->getSummaryCount() > 0) {
			if($show_checkout_btn == $helper::BTN_SHOW_BSECURE_BOTH && $module_enabled){

				?>
				
			    <a href="javascript:;" class="minicart-area bsecure-checkout-button"><img    data-role="proceed-to-checkout"
		            title="<?php echo  __($title); ?>"
		            alt="<?php  echo  __($title); ?>"            
		            class="primary checkout"
		            src="<?php echo $this->getViewFileUrl('Bsecure_UniversalCheckout::images/buy-with-bsecure-black.svg'); ?>"
		             /></a>

			<?php }
		} ?>
       </div>

       <!-- ko template: getTemplate() --><!-- /ko -->
       <script type="text/x-magento-init">
         {
             "#block-cart-list": {
                 "Magento_Ui/js/core/app": <?php /* @escapeNotVerified */ echo $block->getJsLayout();?>
             }
         }
     </script>
   </div>
</div>


