<?php

$moduleEnabled = $block->getBsecureSettings('enable');
$bsecureBtnShowLogin = $block->
                    getBsecureSettings('bsecure_button_show_on_login');
$btnBsecureLogin = 'Bsecure_UniversalCheckout::images/login-with-bsecure.jpg';
    
if ($bsecureBtnShowLogin == 1 && $moduleEnabled == 1) {
    ?>
        
        <a href="<?= $block->escapeHtmlAttr($block->getUrl('bsecure/index/bsecurelogin')); ?>" 
            class="bsecure-login-button">
            <img data-role="bsecure-login"
                title="<?= $block->escapeHtmlAttr(__("Login with bSecure")); ?>"
                alt="<?= $block->escapeHtmlAttr(__("Login with bSecure")); ?>"               
                class=""
                src="<?=
                $block->escapeHtmlAttr($block->getViewFileUrl($btnBsecureLogin));
                ?>"
                 /></a>

    <?php } ?>
