<?php 

    $helper = $this->helper('Bsecure\UniversalCheckout\Helper\Data');    
    $moduleEnabled = $helper->getConfig('universalcheckout/general/enable');
    $bsecureBtnShowLogin = $helper->getConfig('universalcheckout/general/bsecure_button_show_on_login');
    
    if ($bsecureBtnShowLogin == 1 && $moduleEnabled == 1) {
        ?>
        
        <a href="<?php echo $block->escapeHtmlAttr($this->getUrl('bsecure/index/bsecurelogin')); ?>" 
            class="bsecure-login-button">
            <img data-role="bsecure-login"
                title="<?php echo  $block->escapeHtmlAttr(__("Login with bSecure")); ?>"
                alt="<?php  echo  $block->escapeHtmlAttr(__("Login with bSecure")); ?>"               
                class=""
                src="<?php 
                echo $block->escapeHtmlAttr($this->getViewFileUrl('Bsecure_UniversalCheckout::images/login-with-bsecure.jpg'));//phpcs:ignore
                 ?>"
                 /></a>

    <?php } ?>
