<?php

/** @var $block \Bsecure\UniversalCheckout\Block\Checkout */
/** @var \Magento\Checkout\Block\Onepage\Link $link */

if ($block->getOnePageLink()->isPossibleOnepageCheckout()):
    $bsecureHelper      = $block->getBsecureHelper();
    $title = $block->
             getBsecureSettings('bsecure_title');
    $moduleEnabled = $block->
                     getBsecureSettings('enable');
    $showCheckoutBtn =  $block->
                        getBsecureSettings('show_checkout_btn');

    if ($moduleEnabled) {
        if ($showCheckoutBtn == $bsecureHelper::BTN_SHOW_BSECURE_ONLY
         || $showCheckoutBtn == $bsecureHelper::BTN_SHOW_BSECURE_BOTH) {
            ?>
        
            <a href="javascript:;" class="bsecure-checkout-button"><img data-role="proceed-to-checkout"
            title="<?=  $block->escapeHtmlAttr(__($title)); ?>"
            alt="<?=  $block->escapeHtmlAttr(__($title)); ?>"           
            class="primary checkout"
            src="<?=
            $block->escapeHtmlAttr($block->getViewFileUrl($bsecureHelper::BTN_BUY_WITH_BSECURE));
            ?>"
             /></a>

             <?php
                          
                if ($showCheckoutBtn == $bsecureHelper::BTN_SHOW_BSECURE_BOTH) {
                    echo $block->getLayout()->createBlock($block->getOnePageLinkPath())
                    ->setTemplate("Magento_Checkout::onepage/link.phtml")
                    ->toHtml();
                }
                ?>

        <?php }
    } else { ?>
        <?= $block->getLayout()->
                createBlock($block->getOnePageLinkPath())
                ->setTemplate("Magento_Checkout::onepage/link.phtml")
                ->toHtml();
        ?>

    <?php }
endif;?>
